### ISSUE TITLE
Version 2.0 Roadmap/WishList

### ISSUE THREAD

**Issue by radssh** [radssh/radssh#49]
Basic ToDo list for upcoming 2.0 release.

- [ ] Create RadSSHConnection class for integrating lots of things other than `paramiko.Transport` object that the cluster dict currently holds.

- [ ] Better command line arg parsing, including ssh style `-o Option=Value` settings compatible with OpenSSH client command line

- [ ] Formalize Plugin as extensible class

- [ ] Switch from `netaddr` to Python 3 Standard Library `ipaddress` module

- [ ] Install scripts for shell (and other utils) as wrapper entry_points 

- [ ] Custom "real" authentication logic that can support Multi-factor authentication and certificates outside Paramiko's default implementation

- [ ] True support for pre-connection variables 

- [ ] Add support for Ansible inventory mechanism to provide cluster connection and variable info and values

**Comment by radssh** [comment]
Open to additional suggestions from the floor. 😺

**Comment by mckellyln** [comment]
A dedup output option :-)

**Comment by radssh** [comment]
dedup added to list.
